name: .NET with Node.js 20

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.101

      - name: Restore dependencies
        run: dotnet restore ./ClassLibraryProject/YourProjectName.csproj # Replace YourProjectName with the actual name

      - name: Build
        run: dotnet build ./ClassLibraryProject/YourProjectName.csproj # Replace YourProjectName with the actual name

      - name: Test
        run: dotnet test ./ClassLibraryProject/YourTestsFolder/YourTestProjectName.csproj # Replace YourTestsFolder and YourTestProjectName with the actual names
